Bcu 8#suport kubernetes engine
bizflycloud/bizflyctl pull request #16
Opened 2021-03-12 13:17 UTC by tung491

2021-03-13 01:37 UTC, greatbn commented on cmd/kubernetes.go
> +- Using config file example: ./bizflycloud kubernetes create --config-file create_cluster.json`,
use yaml for easier reading and editing

2021-03-13 02:24 UTC, pmint93 commented on cmd/kubernetes.go
> +		fmt.Printf("Delete the Kubernetes cluster successfully")
Cluster is in the process of being deleted

2021-03-13 02:24 UTC, pmint93 commented on cmd/kubernetes.go
> +		fmt.Println("Recycling node successfully")
Node is recycling now

2021-03-13 02:24 UTC, pmint93 commented on cmd/kubernetes.go
> +		fmt.Println("Delete worker pool successfully")
Worker pool is in the process of being deleted

2021-03-13 02:24 UTC, pmint93 commented on cmd/kubernetes.go
> +		fmt.Println("Update worker pool successfully")
Worker pool is updating now

2021-03-13 02:24 UTC, pmint93 commented on cmd/kubernetes.go
> +		fmt.Println("Delete worker pool node successfully")
Node successfully deleted

2021-03-13 02:27 UTC, pmint93 commented on cmd/kubernetes.go
> +	getKubeConfig.PersistentFlags().StringVar(&outputKubeConfigFilePath, "output-path", ".", "Output path")
should be --output or -o

2021-03-14 14:07 UTC, greatbn requested changes

2021-03-14 14:07 UTC, greatbn commented on cmd/kubernetes.go
> +- Using flag example: ./bizfly kubernetes add-workerpool xfbxsws38dcs8o94 --worker-pool name=testworkerpool,flavor=nix.3c_6g,profile_type=premium,volume_type=PREMIUM-HDD1,volume_size=40,availability_
please fix the example ?

2021-03-14 14:07 UTC, greatbn commented on cmd/kubernetes.go
> +	Use:   "get-kubeconfig",
I think we should not use `-` in the command line.

2021-03-14 14:07 UTC, greatbn commented on cmd/kubernetes.go
> +	Use:   "worker-pool",
use workerpool instead

2021-03-14 14:07 UTC, greatbn commented on cmd/kubernetes.go
> +	Use:   "get-kubeconfig",
how about `bizfly kubernetes kubeconfig get <cluster id>`

2021-03-15 07:27 UTC, merged